name: Update json  
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  update:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Create local changes
        run: |
          pip3 install -r scraper/requirements.txt 
          python scraper/src/scraper.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -am "Update json"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
